### ISSUE TITLE
using os.UserHomeDir() instead of a third party package

### ISSUE THREAD

**Issue by uguremirmustafa** [gophercises/task#11]
I am new to golang territory but I think we have what we need in `os` standard library for getting the user's home directory.

Am I missing something?

[relevant docs](https://pkg.go.dev/os#UserHomeDir)

**Comment by joncalhoun** [comment]
At a glance it looks like this would work fine, but I haven't really tested it to see what the differences are and I recorded the exercise so long ago I don't recall why I opted to use a third party library instead of this function. It is possible I just didn't realize that it existed in the std lib at the time.
